backend:
  name: git-gateway

media_folder: media_folder

collections:
  - name: post
    label: Projekt
    folder: projects
    create: true
    fields:
      - {name: title, label: Namn}
      - {name: body, label: Beskrivning, widget: markdown}