backend:
  name: git-gateway

media_folder: "media_folder"

collections:
  - name: "post"
    label: "Project"
    folder: "projects"
    create: true
    fields:
      - {label: "Namn", name: "name", widget: "string"}
      - {label: "Beskrivning", name: "body", widget: "markdown"}
