backend:
  name: git-gateway

media_folder: media_folder

collections:
  - name: project
    label: Projekt
    folder: projects
    create: true
    fields:
      - {name: title, label: Namn}
      - {name: text, label: Beskrivning, widget: text}
      - {name: body, label: Projekt info, widget: markdown}