backend:
  name: git-gateway

media_folder: "media_folder"

collections:
  - name: "projects"
    label: "Project"
    folder: "projects"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Publish Date", name: "datestart", widget: "datetime"}
      - {label: "End Date", name: "dateend", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
